/**
 * Denver Engineering — Ava Estimating Agent (v10.0.0)
 * ─────────────────────────────────────────────────────
 * Orchestrates: BIM quantity summary → cost lookup → estimate assembly.
 *
 * Uses Claude to:
 *   1. Map IFC element types to CSI sections when no exact mapping exists
 *   2. Estimate unit costs when no cost_item exists in the DB
 *   3. Generate a narrative summary of the estimate
 *
 * Falls back to deterministic rules when AI is unavailable or disabled.
 */
import Anthropic from '@anthropic-ai/sdk'
import { tenantQuery } from '../../db/pool'
import {
  getModelQuantitySummary,
} from '../bim/bimElementService'
import { autoTakeoffFromBim } from './estimatingService'
import {
  createEstimate,
  addEstimateLines,
  findCostItem,
  type EstimateLineDraft,
} from './estimatingService'

// ─── Types ────────────────────────────────────────────────────────────────────

export interface AvaEstimateInput {
  tenantId:   string
  modelId:    string
  projectId?: string
  region?:    string
  name?:      string
  createdBy:  string
}

export interface AvaEstimateResult {
  estimate_id:   string
  line_count:    number
  total_cost:    number
  currency:      string
  generated_by:  'ava'
  summary?:      string
  warnings:      string[]
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

const FALLBACK_RATES: Record<string, { material: number; labor: number; equipment: number }> = {
  '03 30 00': { material: 8.50,  labor: 6.20,  equipment: 1.80 },  // Concrete ($/SF or $/CY)
  '04 20 00': { material: 12.00, labor: 9.00,  equipment: 0.50 },  // Masonry ($/SF)
  '05 12 00': { material: 18.00, labor: 14.00, equipment: 2.00 },  // Steel ($/LF)
  '07 31 00': { material: 5.50,  labor: 3.80,  equipment: 0.30 },  // Roofing ($/SF)
  '08 14 00': { material: 380,   labor: 120,   equipment: 10 },    // Doors ($/EA)
  '08 51 00': { material: 280,   labor: 95,    equipment: 5 },     // Windows ($/EA)
  '22 10 00': { material: 22,    labor: 18,    equipment: 1 },     // Plumbing pipe ($/LF)
  '22 40 00': { material: 180,   labor: 90,    equipment: 5 },     // Plumbing fixtures ($/EA)
  '23 31 00': { material: 15,    labor: 12,    equipment: 1 },     // HVAC duct ($/LF)
  '26 05 00': { material: 4,     labor: 6,     equipment: 0.5 },   // Electrical conduit ($/LF)
  '26 27 00': { material: 18,    labor: 25,    equipment: 1 },     // Outlets ($/EA)
  '26 51 00': { material: 95,    labor: 45,    equipment: 2 },     // Lighting ($/EA)
}

function fallbackRate(csi: string) {
  return FALLBACK_RATES[csi] ?? { material: 10, labor: 8, equipment: 1 }
}

// ─── Main agent function ──────────────────────────────────────────────────────

export async function runEstimatingAgent(input: AvaEstimateInput): Promise<AvaEstimateResult> {
  const warnings: string[] = []

  // 1. Auto-extract quantities from BIM elements
  await autoTakeoffFromBim(input.tenantId, input.modelId, input.createdBy)

  // 2. Get quantity summary grouped by IFC type
  const summary = await getModelQuantitySummary(input.tenantId, input.modelId)
  if (!summary.length) {
    warnings.push('No BIM elements found — estimate will be empty')
  }

  // 3. Get model name for estimate label
  const modelRes = await tenantQuery(input.tenantId,
    'SELECT name FROM bim_models WHERE id=$1 AND tenant_id=$2',
    [input.modelId, input.tenantId])
  const modelName = (modelRes.rows[0]?.name as string) ?? 'BIM Model'

  // 4. Create the estimate header
  const { id: estimateId } = await createEstimate(
    input.tenantId,
    {
      project_id:    input.projectId,
      model_id:      input.modelId,
      name:          input.name ?? `${modelName} — Ava Estimate`,
      estimate_type: 'construction',
      region:        input.region,
      generated_by:  'ava',
    },
    input.createdBy,
  )

  // 5. Get takeoff items generated by autoTakeoffFromBim
  const takeoffRes = await tenantQuery(input.tenantId,
    `SELECT id, csi_section, description, quantity, unit
     FROM takeoff_items WHERE tenant_id=$1 AND model_id=$2 AND source='bim'`,
    [input.tenantId, input.modelId])

  // 6. Build estimate lines: cost lookup first, fallback second
  const lines: EstimateLineDraft[] = []
  let aiCostLines = 0

  for (const row of takeoffRes.rows) {
    const csi = row.csi_section as string | null
    let costItem = csi
      ? await findCostItem(input.tenantId, csi, row.unit as string, input.region)
      : null

    if (costItem) {
      lines.push({
        takeoff_id:     row.id as string,
        cost_item_id:   costItem.id,
        csi_section:    csi ?? undefined,
        description:    row.description as string,
        quantity:       parseFloat(row.quantity as string),
        unit:           row.unit as string,
        unit_material:  costItem.material_cost,
        unit_labor:     costItem.labor_cost,
        unit_equipment: costItem.equipment_cost,
      })
    } else {
      // Use fallback rates — flag for AI enrichment
      const rates = fallbackRate(csi ?? '')
      lines.push({
        takeoff_id:    row.id as string,
        csi_section:   csi ?? undefined,
        description:   row.description as string,
        quantity:      parseFloat(row.quantity as string),
        unit:          row.unit as string,
        unit_material:  rates.material,
        unit_labor:     rates.labor,
        unit_equipment: rates.equipment,
      })
      aiCostLines++
    }
  }

  if (aiCostLines > 0) {
    warnings.push(`${aiCostLines} line(s) used fallback rates — no matching cost item in library`)
  }

  await addEstimateLines(input.tenantId, estimateId, lines)

  // 7. Optionally enrich with Claude narrative (non-blocking)
  let summary_text: string | undefined
  const apiKey = process.env['ANTHROPIC_API_KEY']
  if (apiKey && lines.length > 0) {
    try {
      summary_text = await generateEstimateSummary(summary, lines, modelName)
    } catch {
      warnings.push('AI narrative generation skipped — Anthropic API unavailable')
    }
  }

  // 8. Read back total
  const finalRes = await tenantQuery(input.tenantId,
    'SELECT total_cost, currency FROM estimates WHERE id=$1',
    [estimateId])
  const final = finalRes.rows[0]

  // 9. Record feedback for adaptive learning
  await tenantQuery(input.tenantId,
    `INSERT INTO learning_feedback
       (tenant_id, feedback_type, source_id, source_type, agent_type,
        signal, outcome, context, recorded_by)
     VALUES ($1,'estimate',$2,'estimates','estimating_agent','neutral','unknown',$3,'agent')`,
    [
      input.tenantId,
      estimateId,
      JSON.stringify({ line_count: lines.length, total_cost: final?.total_cost, warnings }),
    ]).catch(() => {}) // non-blocking

  return {
    estimate_id:  estimateId,
    line_count:   lines.length,
    total_cost:   parseFloat(final?.total_cost ?? '0'),
    currency:     final?.currency ?? 'USD',
    generated_by: 'ava',
    summary:      summary_text,
    warnings,
  }
}

// ─── Claude narrative summary ─────────────────────────────────────────────────

async function generateEstimateSummary(
  quantitySummary: { ifc_type: string; discipline: string | null; count: number }[],
  lines:            EstimateLineDraft[],
  modelName:        string,
): Promise<string> {
  const client   = new Anthropic()
  const total    = lines.reduce((s, l) => s + l.quantity * (l.unit_material + l.unit_labor + l.unit_equipment), 0)
  const topLines = lines
    .map(l => ({ desc: l.description, cost: l.quantity * (l.unit_material + l.unit_labor + l.unit_equipment) }))
    .sort((a, b) => b.cost - a.cost)
    .slice(0, 5)

  const prompt = `You are a senior cost estimator. Summarize this construction estimate in 2-3 sentences for a project manager.

Model: ${modelName}
Element types: ${quantitySummary.map(s => `${s.ifc_type} (${s.count})`).join(', ')}
Total estimated cost: $${total.toLocaleString('en-US', { maximumFractionDigits: 0 })}
Top cost drivers: ${topLines.map(l => `${l.desc} ($${l.cost.toLocaleString('en-US', { maximumFractionDigits: 0 })})`).join(', ')}

Write a clear, professional 2-3 sentence summary. No markdown.`

  const msg = await client.messages.create({
    model:      'claude-haiku-4-5',
    max_tokens: 200,
    messages:   [{ role: 'user', content: prompt }],
  })

  const block = msg.content[0]
  return block?.type === 'text' ? block.text : ''
}
