-- ============================================================
-- JARVIS EPC — Migration 013: Field Sync Operations Log
-- v4.31.0 | Idempotency ledger for offline-captured mutations
--
-- Offline-first field workflows (PWA, mobile) queue mutations
-- locally while disconnected, then replay them in a batch when
-- connectivity returns. Because network flakiness can cause the
-- same batch to be submitted twice, each operation carries a
-- client-generated UUID (client_op_id) that this table stores
-- along with the server's result. Retries that hit an already-
-- processed client_op_id return the cached result instead of
-- re-executing the mutation.
--
-- One row = one attempt at one operation. The (tenant_id,
-- client_op_id) UNIQUE constraint is the dedup guarantee.
-- ============================================================

CREATE TABLE field_sync_operations (
  id             UUID         PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id      UUID         NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,

  -- Idempotency key: generated by the client when the mutation is first
  -- captured offline. Must be a UUID so collisions are a cryptographic
  -- near-impossibility.
  client_op_id   UUID         NOT NULL,

  resource       VARCHAR(64)  NOT NULL,   -- e.g. 'action_items', 'daily_logs'
  op             VARCHAR(16)  NOT NULL,   -- 'create' | 'update'

  -- 'success' | 'conflict' | 'error'
  status         VARCHAR(16)  NOT NULL,

  -- ID of the underlying resource row the operation created / targeted.
  resource_id    UUID,

  -- What the client sent. Kept for troubleshooting.
  request_body   JSONB        NOT NULL DEFAULT '{}',

  -- What the server returned (resource row on success; conflict row on
  -- conflict; null + error_text on error). Clients can replay this to
  -- reconstruct local state after loss of the offline queue.
  response_body  JSONB,
  error_text     TEXT,

  created_by     UUID         REFERENCES users(id) ON DELETE SET NULL,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

  CONSTRAINT field_sync_ops_dedup UNIQUE (tenant_id, client_op_id)
);

CREATE INDEX idx_field_sync_tenant
  ON field_sync_operations(tenant_id, created_at DESC);

CREATE INDEX idx_field_sync_resource
  ON field_sync_operations(tenant_id, resource, created_at DESC);

ALTER TABLE field_sync_operations ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_field_sync_ops ON field_sync_operations
  USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid);
