/**
 * Denver Engineering — Capability Truth Registry
 * ─────────────────────────────────────────────────────────────────────────────
 * A machine-readable, honesty-first inventory of every user-reachable surface.
 * Each entry states what a surface ACTUALLY does — verified against source,
 * backend routes, and this session's prior traced audits (see
 * audit/INDEPENDENT_AUDIT_2026-07-02.md and audit/evidence/) — not what its
 * label implies.
 *
 * This file is the source of truth enforced by scripts/validate-capability-registry.mjs
 * (CI job "feature-truth-guard") and src/__tests__/config/capabilityRegistry.test.ts.
 *
 * ── Verification tiers (honesty about HOW a status was established) ──
 *   'runtime'  — exercised live (server + real request/DB) this or a prior session
 *   'code'     — determined from source + backend route tracing (no live workflow run)
 *   'audit'    — carried from a committed evidence doc in audit/ with file:line proof
 *   'blocked'  — verification genuinely blocked (state the blocker in `limitations`)
 *
 * NOTE ON RUNTIME VERIFICATION LIMITS: the local dev database is empty (0 tenants,
 * 0 users) and the login screen is a stale PIN form that does not match the
 * email/password backend (itself a finding — see id 'login-screen-stale'). Deep
 * multi-tenant workflow verification was therefore constrained; workflow-DEPTH
 * classifications lean on 'code'/'audit' evidence, and that is stated per-entry
 * rather than overclaimed as 'runtime'.
 */

export type CapabilityStatus =
  | 'VERIFIED_NATIVE'          // frontend + backend + persistence in THIS repo, real behavior
  | 'VERIFIED_EXTERNAL'        // depends on an external service; integration path implemented + exercised
  | 'DETERMINISTIC_AUTOMATION' // rules / thresholds / scoring / workflow — NOT generative AI
  | 'PREDICTIVE_MODEL'         // statistical/heuristic inference (state whether validated)
  | 'GROUNDING_OR_RAG'         // LLM answering from retrieved project documents, with citations
  | 'DRAWING_GENERATOR'        // produces a real drawing/diagram; implies NO engineering calc
  | 'EXTERNAL_SHELL'           // UI expecting an external calc/intelligence not proven to implement it
  | 'UI_ONLY'                  // renders; no meaningful backend/persistence
  | 'PLACEHOLDER_OR_SYNTHETIC' // outputs are random/hard-coded/synthetic presented as results
  | 'PARTIAL'                  // meaningful part works; a required segment is incomplete
  | 'BROKEN_OR_DEAD'           // dead nav/route/action, missing backend, or cannot fulfil its purpose
  | 'NOT_VERIFIED'             // verification genuinely blocked

export type VerificationTier = 'runtime' | 'code' | 'audit' | 'blocked'

export interface Capability {
  id: string
  name: string
  route?: string                 // nav id (see config/navigation.ts) or hidden TAB_MAP id
  navigationSection?: string
  component?: string
  status: CapabilityStatus
  verification: VerificationTier
  llmUsed: boolean
  deterministicRulesUsed: boolean
  predictiveModelUsed: boolean
  engineeringCalculation: boolean
  calculationValidated: boolean
  drawingGeneration: boolean
  backendLocation?: string       // repo path of the backing route/service, or undefined
  externalDependency?: string    // required external service, or undefined
  productionSuitable: boolean
  engineerReviewRequired: boolean
  honestyIssue?: string          // user-facing claim that is misleading, if any
  limitations: string[]
  evidence: string[]
}

/**
 * IN_NAV routes that are DELIBERATELY absent from the registry would fail the
 * guard. Every nav id must appear here. Hidden/legacy TAB_MAP-only routes are
 * included where reachable. Intentional exclusions are listed in EXCLUDED below.
 */
export const CAPABILITIES: Capability[] = [
  // ─── Personal ────────────────────────────────────────────────────────────
  {
    id: 'focus', name: 'Focus', route: 'focus', navigationSection: 'personal',
    component: 'src/components/copilot/CopilotView.tsx',
    status: 'DETERMINISTIC_AUTOMATION', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes (copilot focus)', externalDependency: undefined,
    productionSuitable: true, engineerReviewRequired: false,
    honestyIssue: 'Presented in an "AI" family; it ranks live cross-module signals by deterministic rules, not an LLM.',
    limitations: ['Deterministic ranking, not generative AI.'],
    evidence: ['CopilotView.tsx header: "ranking live cross-module signals ... Deterministic"'],
  },
  {
    id: 'mywork', name: 'My Work', route: 'mywork', navigationSection: 'personal',
    component: 'src/components/myWork/MyWorkView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'audit',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/services/myWork/myWorkService.ts, api/routes/myWork.ts',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Depended on change_orders schema fix (083) — landed on main via PR #18.'],
    evidence: ['CLOSURE_EVIDENCE_2026-07-02.md P0-03; real tenantQuery reads across rfis/punch/capa/actions/inspections/submittals/change_orders'],
  },
  {
    id: 'actions', name: 'Actions', route: 'actions', navigationSection: 'personal',
    component: 'src/components/ActionItemsView.tsx',
    status: 'PARTIAL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes/actions.ts (mounted, but ActionItemsView never calls it)',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Downgraded from VERIFIED_NATIVE (independent review 2026-07-21): the routed component ActionItemsView.tsx makes zero backend calls — its only source is useBizStore(selectActionItems), a collection store.ts:235-238 documents as never hydrated. A real actions backend (api/routes/actions.ts) exists but this route does not reach it. Same defect the registry grades engineering-hub PARTIAL for.',
    limitations: ['Route renders from the non-hydrated biz store, not the backend. SLA/escalation rule logic exists server-side but is unreached from this view.'],
    evidence: ['ActionItemsView.tsx:203 useBizStore(selectActionItems); store.ts:235-238 non-hydrated collections; independent review 2026-07-21'],
  },
  {
    id: 'notifications', name: 'Notifs', route: 'notifications', navigationSection: 'personal',
    component: 'src/components/notifications/NotificationsView.tsx',
    status: 'PARTIAL', verification: 'audit',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/services/notifications/notificationWorker.ts',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Alert center renders alerts; outbound delivery channels (in-app/email/Slack) were stubs — now return honest failure (P0-08) rather than fake success, but real delivery is still not implemented.',
    limitations: ['In-app/email/Slack delivery not implemented; stubs now fail honestly (P0-08 fix).'],
    evidence: ['CLOSURE_EVIDENCE_2026-07-02.md P0-08; notificationWorker.ts'],
  },

  // ─── Project Setup ───────────────────────────────────────────────────────
  {
    id: 'setup', name: 'Setup Wizard', route: 'setup', navigationSection: 'setup',
    component: 'src/components/setup/SetupWizardView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'POST /api/v1/projects',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Resumable multi-step flow that creates a real project.'],
    evidence: ['SetupWizardView.tsx header: "initializes a real project (POST /api/v1/projects)"'],
  },
  {
    id: 'projects', name: 'Projects', route: 'projects', navigationSection: 'setup',
    component: 'src/components/ProjectsView.tsx',
    status: 'PARTIAL', verification: 'audit',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'GET /api/v1/projects (list) + useBizStore',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'The list view casts CRM contracts to Project[] (no canonical Project entity in the store); projects collection is now hydrated (P0-10 partial fix) but the entity model is informally reconciled.',
    limitations: ['No single canonical Project entity in the frontend store; contracts cast to Project[].'],
    evidence: ['INDEPENDENT_AUDIT_2026-07-02.md frontend finding; store.ts hydrateProjectsFromBackend (projects only)'],
  },
  {
    id: 'lifecycle', name: 'Lifecycle', route: 'lifecycle', navigationSection: 'setup',
    component: 'src/components/lifecycle/LifecycleView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'GET /api/v1/projects/:id/lifecycle, POST .../gates/:gateKey, POST .../advance',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Gate requirements computed live from records; deterministic.'],
    evidence: ['LifecycleView.tsx header lists the three real endpoints'],
  },
  {
    id: 'crm', name: 'CRM', route: 'crm', navigationSection: 'setup',
    component: 'src/components/CRMView.tsx',
    status: 'PARTIAL', verification: 'audit',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'useBizStore (not hydrated from backend)',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Reads useBizStore leads/customers/proposals, which nothing hydrates from the backend (only the projects collection is hydrated). Empty on a fresh session with no error — indistinguishable from "no data".',
    limitations: ['useBizStore CRM collections never hydrated from /api (P0-10 open beyond projects).'],
    evidence: ['INDEPENDENT_AUDIT_2026-07-02.md P0-10; store.ts hydrates projects only'],
  },
  {
    id: 'proposals', name: 'Proposals', route: 'proposals', navigationSection: 'setup',
    component: 'src/components/proposals/ProposalsView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes (proposals REST)',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Kanban pipeline + line-item costing.'],
    evidence: ['ProposalsView.tsx (dedicated component under proposals/ with REST calls)'],
  },
  {
    id: 'team', name: 'Team', route: 'team', navigationSection: 'setup',
    component: 'src/components/team/TeamView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes (team/members REST)',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: [],
    evidence: ['TeamView.tsx header: roster grid, member detail, add/assign'],
  },

  // ─── Planning ────────────────────────────────────────────────────────────
  {
    id: 'scheduleimport', name: 'Import Schedule', route: 'scheduleimport', navigationSection: 'planning',
    component: 'src/components/schedule/ScheduleImportView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'audit',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/services/schedule/{xerParser,mspParser}.ts',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['P6 XER + MS Project XML parsing; hardening covered by scheduleParsers.test.ts (17 tests).'],
    evidence: ['scheduleParsers.test.ts; CLOSURE_EVIDENCE schedule-import commit'],
  },
  {
    id: 'forecast', name: 'Schedule Forecast', route: 'forecast', navigationSection: 'planning',
    component: 'src/components/schedule/ScheduleForecastView.tsx',
    status: 'PREDICTIVE_MODEL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: true,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes (schedule forecast); CPM dependency network',
    productionSuitable: true, engineerReviewRequired: false,
    honestyIssue: 'Monte Carlo completion forecast — a statistical simulation over the real CPM network, not an LLM. Should not be branded generative "AI".',
    limitations: ['Statistical Monte Carlo over CPM; not a trained ML model, not LLM.'],
    evidence: ['ScheduleForecastView.tsx header: "Monte Carlo completion forecast ... over the real CPM dependency network"'],
  },
  {
    id: 'riskregister', name: 'Risk Register', route: 'riskregister', navigationSection: 'planning',
    component: 'src/components/riskRegister/RiskRegisterView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes/riskRegister.ts + api/services/riskRegister/riskService.ts',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Re-verified at code+contract tier after the route-shadow fix merged (PR #22, merge 63861eb): the stale risksRouter is removed, so riskRegisterRouter now owns list/get/create/update/close, and riskService writes the migrated risks columns (probability/impact/cost_exposure/mitigation_plan/contingency_plan). No live-DB or browser E2E was run in this pass — persistence and UI states are proven by code + merged regression tests, not runtime.'],
    evidence: ['PR #22 merge 63861eb (fix 4842936 + anti-regression tests 3560d0e): api/__tests__/routeShadowRegression.test.ts asserts production mount order resolves to riskRegisterRouter, create maps title/category/probability/impact/costExposure/mitigationPlan to the service, list returns {risks}, and stale routes/risks.ts is gone; riskService.ts uses mitigation_plan/cost_exposure, not the pre-067 likelihood column'],
  },
  {
    id: 'budget', name: 'Budget', route: 'budget', navigationSection: 'planning',
    component: 'src/components/BudgetView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'runtime',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes/budgets.ts',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Mutating endpoints lack value-level validation (P2-15, non-blocking).'],
    evidence: ['BudgetView.tsx REST calls; INDEPENDENT_AUDIT frontend finding lists it as live /api-wired'],
  },
  {
    id: 'meetings', name: 'Meetings', route: 'meetings', navigationSection: 'planning',
    component: 'src/components/meetings/MeetingsView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes (meetings REST)',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Draft → Published workflow, agenda + auto-linked actions.'],
    evidence: ['MeetingsView.tsx header'],
  },

  // ─── Engineering ─────────────────────────────────────────────────────────
  {
    id: 'feed', name: 'FEED', route: 'feed', navigationSection: 'engineering',
    component: 'src/components/FeedView.tsx',
    status: 'PARTIAL', verification: 'runtime',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'useBizStore (finance journal)',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Labeled "FEED" as engineering-lifecycle step 1 (implies Front-End Engineering Design), but the actual screen is a FINANCIAL journal (Invoice/Expense/Journal, "+ Journal Entry"). Content does not match the label.',
    limitations: ['Mislabeled; store-backed finance feed, not engineering design.'],
    evidence: ['Runtime this session: /#feed renders Invoice/Expense/Journal + "No financial activity yet"'],
  },
  {
    id: 'processdesign', name: 'Process Design', route: 'processdesign', navigationSection: 'engineering',
    component: 'src/components/ProcessDesignView.tsx',
    status: 'EXTERNAL_SHELL', verification: 'audit',
    llmUsed: true, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: true, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'POST /api/v1/mcp/execute → AVA_MCP_URL (unset by default)',
    externalDependency: 'Ava MCP orchestrator (AVA_MCP_URL) — blank in .env.example',
    productionSuitable: false, engineerReviewRequired: true,
    honestyIssue: 'Presents "ProcessDesignPro / AI Process Engineering" with equipment sizing tools; routes to an external Ava MCP orchestrator that is an agent/task dispatcher, not a proven calculation engine, and is unconfigured by default (503 ava_not_configured).',
    limitations: ['No validated process-calc backend reachable; MCP target unconfigured; outputs must not be treated as engineering.'],
    evidence: ['FEATURES.md engineering-tools honest status; INDEPENDENT_AUDIT MCP audit (34/43 tools 503 without AVA_MCP_URL)'],
  },
  {
    id: 'calc', name: 'Calcs', route: 'calc', navigationSection: 'engineering',
    component: 'src/components/CalcView.tsx',
    status: 'PARTIAL', verification: 'audit',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: true, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'mixed: EPC calculators (deterministic, in-repo) + discipline design tools (unvalidated in-app math and/or external shell) + P&ID generator (public/tools/denver/*, broken)',
    externalDependency: 'Ava MCP orchestrator for discipline design tools',
    productionSuitable: false, engineerReviewRequired: true,
    honestyIssue: 'Bundles three truth levels under one "Calcs" surface: real EPC calculators (EVM/schedule/manpower/unit-rate); discipline design tools whose in-app math is unvalidated hand-rolled formulas with hard-coded fudge factors AND/OR fabricated Math.random() output presented as results (see DENVER_ENGINEERING_TOOLS_STATUS.md); and a P&ID generator that is BROKEN (see pid-pfd-generator). Correction (independent review 2026-07-21): the prior claim that "the drawing generator is trustworthy" is withdrawn — it is not. Only the EPC calculators are trustworthy. Also note the discipline tools emit false compliance toasts ("per NFPA 13", "per NEC Article 220") and a fake "Pareto-optimal solution found" notification, and NO in-app warning is rendered; "Save to Project" persists synthetic numbers into the project record.',
    limitations: ['Discipline design-tool math is unvalidated or synthetic; P&ID generator is broken; no runtime disclaimer shown to the user (see DENVER_ENGINEERING_TOOLS_STATUS.md).'],
    evidence: ['CalcView.tsx header: "EPC Calculators (preserved)"; FEATURES.md engineering-tools table'],
  },
  {
    id: 'drawings', name: 'Drawings', route: 'drawings', navigationSection: 'engineering',
    component: 'src/components/DrawingsView.tsx',
    status: 'PARTIAL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes/drawings.ts (register/revisions/markups — real, mounted server.ts:555)',
    productionSuitable: true, engineerReviewRequired: false,
    honestyIssue: 'Downgraded from VERIFIED_NATIVE (independent review 2026-07-21): register, revisions, and markups are genuinely wired, but the in-app PDF viewer iframe (DrawingsView.tsx:162) points at /api/v1/documents/:id/file, which does not exist — the real route is /api/v1/files/documents/:id (no /file suffix). The request falls into the SPA catch-all (server.ts:678) and silently renders HTML instead of a PDF.',
    limitations: ['Sheet register + markups + revisions work. Embedded PDF viewer 404s (wrong route) and renders SPA HTML instead of the document.'],
    evidence: ['DrawingsView.tsx:162 iframe src; filesRouter mounted at /api/v1/files (server.ts:530); no :id/file route exists; independent review 2026-07-21'],
  },
  {
    id: 'bim', name: 'BIM', route: 'bim', navigationSection: 'engineering',
    component: 'src/components/BIMViewerView.tsx',
    status: 'VERIFIED_EXTERNAL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes (bim register) + xeokit viewer (CDN)',
    externalDependency: 'xeokit 3D viewer via CDN',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['IFC/glTF register + web 3D viewer + clash issue tracking; viewer lib is CDN-loaded.'],
    evidence: ['BIMViewerView.tsx header: "web-based 3D viewer via xeokit CDN"'],
  },
  {
    id: 'hub', name: 'Eng Hub', route: 'hub', navigationSection: 'engineering',
    component: 'src/components/HubView.tsx',
    status: 'PARTIAL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'useBizStore aggregation (mostly non-hydrated)',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Cross-domain dashboard aggregating useBizStore collections; most are never hydrated from backend, so tiles read empty on a fresh session. Also appears in the sidebar Engineering section but not the engineering lifecycle stepper (a reference tool, not a stage — see workflows.ts).',
    limitations: ['Aggregates non-hydrated store collections.'],
    evidence: ['HubView.tsx reads useBizStore selectors; workflows.ts engineering-flow comment'],
  },
  {
    id: 'fixlibrary', name: 'Fix Library', route: 'fixlibrary', navigationSection: 'engineering',
    component: 'src/components/FixLibraryView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes (fix library REST) — tenant troubleshooting corpus',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Reference tool (browse/search/create fixes); feeds Ask Jarvis retrieval. Not a lifecycle stage.'],
    evidence: ['FixLibraryView.tsx header: "Tenant-owned troubleshooting corpus"'],
  },
  {
    id: 'rfis', name: 'RFIs', route: 'rfis', navigationSection: 'engineering',
    component: 'src/components/RFIsView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'runtime',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes (RFIs REST) + rfi/RfiCopilotPanel',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['RFI log with review + overdue tracking; render verified live this session (empty state).'],
    evidence: ['Runtime this session: /#rfis rendered KPI tiles + "No RFIs found"'],
  },
  {
    id: 'submittals', name: 'Submittals', route: 'submittals', navigationSection: 'engineering',
    component: 'src/components/SubmittalsView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'runtime',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes/submittals (/api/v1/submittals)',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Full submittal workflow; render verified live this session (empty state).'],
    evidence: ['SubmittalsView.tsx header: "Full submittal workflow against /api/v1/submittals"; runtime /#submittals'],
  },

  // ─── Procurement ─────────────────────────────────────────────────────────
  {
    id: 'subcontracts', name: 'Subcontracts', route: 'subcontracts', navigationSection: 'procurement',
    component: 'src/components/procurement/SubcontractView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes (subcontracts REST)',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Bid packages, award, schedule of values.'],
    evidence: ['SubcontractView.tsx header'],
  },
  {
    id: 'procurementrisk', name: 'Procure Risk', route: 'procurementrisk', navigationSection: 'procurement',
    component: 'src/components/procurement/ProcurementRiskView.tsx',
    status: 'DETERMINISTIC_AUTOMATION', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'GET /api/v1/projects/:projectId/procurement-risk',
    productionSuitable: true, engineerReviewRequired: false,
    honestyIssue: 'Named "risk prediction" but is deterministic ranking over purchase orders, not a trained model.',
    limitations: ['Deterministic PO risk ranking + vendor rollup.'],
    evidence: ['ProcurementRiskView.tsx header: "Deterministic."'],
  },
  {
    id: 'vendorscore', name: 'Vendor Scorecard', route: 'vendorscore', navigationSection: 'procurement',
    component: 'src/components/procurement/VendorScorecardView.tsx',
    status: 'DETERMINISTIC_AUTOMATION', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes (vendor scorecard) — synthesized from subcontracts + POs',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Deterministic vendor standing from commitments/billing/on-time delivery.'],
    evidence: ['VendorScorecardView.tsx header: "Deterministic."'],
  },
  {
    id: 'directory', name: 'Directory', route: 'directory', navigationSection: 'procurement',
    component: 'src/components/DirectoryView.tsx',
    status: 'BROKEN_OR_DEAD', verification: 'audit',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'expects props never passed by ContentRouter',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Renders permanently empty regardless of backend health: DirectoryView destructures vendors/customers/POs/contracts/invoices from props, but ContentRouter\'s sharedProps only passes {policy,biz,onNavigate,onAudit,onToast}. Unwired (P0-11, still open on main).',
    limitations: ['Data props never wired; always empty. Not fixed by PR #18.'],
    evidence: ['Confirmed on current main: ContentRouter.tsx sharedProps (5 keys) vs DirectoryView.tsx destructure; INDEPENDENT_AUDIT P0-11'],
  },

  // ─── Construction ────────────────────────────────────────────────────────
  {
    id: 'construction', name: 'Construct', route: 'construction', navigationSection: 'construction',
    component: 'src/components/ConstructionView.tsx',
    status: 'PARTIAL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'composes WView/JobsView (store-backed)',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Hub view composing store-backed sub-views; depends on non-hydrated useBizStore.',
    limitations: ['Aggregation hub over legacy store views.'],
    evidence: ['ConstructionView.tsx imports WView/JobsView'],
  },
  {
    id: 'dailylogs', name: 'Daily Logs', route: 'dailylogs', navigationSection: 'construction',
    component: 'src/components/DailyLogsView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'audit',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes (daily logs REST)',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Weather/crew/equipment/delay/safety; catch block lacks console.error (P2 UX).'],
    evidence: ['DailyLogsView.tsx header "Procore-parity Daily Log"; INDEPENDENT_AUDIT lists as live /api-wired'],
  },
  {
    id: 'field', name: 'Field Svc', route: 'field', navigationSection: 'construction',
    component: 'src/components/FieldOperationsView.tsx',
    status: 'PARTIAL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'composes FeView/WtView (store-backed)',
    productionSuitable: false, engineerReviewRequired: false,
    limitations: ['Offline-capable work orders claimed; composes legacy store sub-views.'],
    evidence: ['FieldOperationsView.tsx imports FeView/WtView'],
  },
  {
    id: 'fieldai', name: 'Field Asst', route: 'fieldai', navigationSection: 'construction',
    component: 'src/components/field/FieldAssistantView.tsx',
    status: 'DETERMINISTIC_AUTOMATION', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'GET /api/v1/projects/:id/field-assistant',
    productionSuitable: true, engineerReviewRequired: false,
    honestyIssue: 'Named "AI Field Assistant" but is deterministic, grounded in inspections+punch+schedule — no LLM.',
    limitations: ['Deterministic answers (due inspections / behind schedule / open in area).'],
    evidence: ['FieldAssistantView.tsx header: "Deterministic, grounded in inspections + punch + schedule."'],
  },
  {
    id: 'timesheets', name: 'Timesheets', route: 'timesheets', navigationSection: 'construction',
    component: 'src/components/timesheets/TimesheetsView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/services/timesheets/timesheetService.ts',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Approve → auto-creates Labor Cost Entry → Cost Control ACWP.'],
    evidence: ['TimesheetsView.tsx header; timesheetService.ts evm_actuals insert (correct columns)'],
  },
  {
    id: 'iot', name: 'IoT Sensors', route: 'iot', navigationSection: 'construction',
    component: 'src/components/iot/IoTDashboard.tsx',
    status: 'VERIFIED_NATIVE', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/services/iot/sensorIngestService.ts',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Registry, readings, sparklines, alert thresholds (deterministic).'],
    evidence: ['IoTDashboard.tsx header; sensor schema verified in INDEPENDENT_AUDIT data-model audit'],
  },

  // ─── Quality ─────────────────────────────────────────────────────────────
  {
    id: 'inspections', name: 'Inspections', route: 'inspections', navigationSection: 'quality',
    component: 'src/components/InspectionsView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes (inspections REST) + CSV export',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Template-driven checklists; deep-link support.'],
    evidence: ['InspectionsView.tsx (useDeepLink, downloadCsv, REST)'],
  },
  {
    id: 'punch', name: 'Punch List', route: 'punch', navigationSection: 'quality',
    component: 'src/components/PunchListView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: '/api/v1/projects/:projectId/... (punch REST)',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Full punch-list workflow.'],
    evidence: ['PunchListView.tsx header: "Full punch-list workflow against /api/v1/..."'],
  },
  {
    id: 'ncr', name: 'NCR / CAPA', route: 'ncr', navigationSection: 'quality',
    component: 'src/components/quality/NcrView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes (ncr/capa REST)',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Non-conformance register + CAPA tracking + deterministic summary.'],
    evidence: ['NcrView.tsx header'],
  },
  {
    id: 'quality', name: 'Quality IQ', route: 'quality', navigationSection: 'quality',
    component: 'src/components/quality/QualityIntelligenceView.tsx',
    status: 'DETERMINISTIC_AUTOMATION', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes (quality intelligence) — from inspections + punch',
    productionSuitable: true, engineerReviewRequired: false,
    honestyIssue: '"IQ" branding implies AI; it is deterministic analytics over inspections + punch items.',
    limitations: ['Deterministic recurring-issue / discipline-score / hotspot analytics.'],
    evidence: ['QualityIntelligenceView.tsx header: "Deterministic."'],
  },

  // ─── Safety ──────────────────────────────────────────────────────────────
  {
    id: 'safety', name: 'Safety', route: 'safety', navigationSection: 'safety',
    component: 'src/components/SafetyView.tsx',
    status: 'PARTIAL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'useBizStore (legacy module)',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Legacy JarvisCore-extracted module reading useBizStore (JHA/incidents/toolbox/permits); store not hydrated from backend.',
    limitations: ['Store-backed; not hydrated.'],
    evidence: ['SafetyView.tsx header: "Extraction of JarvisCore kn() ... four safety domains"'],
  },
  {
    id: 'compliance', name: 'Compliance', route: 'compliance', navigationSection: 'safety',
    component: 'src/components/ComplianceView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes (compliance_tasks) + complianceWatcher service',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Create/complete compliance tasks; auto-fires webhook events via complianceWatcher.'],
    evidence: ['ComplianceView.tsx header'],
  },

  // ─── Commercial ──────────────────────────────────────────────────────────
  {
    id: 'changeorders', name: 'Change Orders', route: 'changeorders', navigationSection: 'commercial',
    component: 'src/components/changeOrders/ChangeOrdersView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes/changeOrders.ts + api/services/changeOrders/changeOrderService.ts',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Re-verified at code+contract tier after the route-shadow fix merged (PR #22, merge 63861eb): the inline change-order routes are removed from budgets.ts, so changeOrdersRouter now owns list/create/patch and the workflow transitions. approve/reject are RBAC-gated to owner/admin/project_manager (AUDIT-P1-12). No live-DB or browser E2E was run in this pass — persistence and UI states are proven by code + merged regression tests, not runtime.'],
    evidence: ['PR #22 merge 63861eb (fix 4842936 + anti-regression tests 3560d0e): api/__tests__/routeShadowRegression.test.ts asserts production mount order resolves list/create to changeOrdersRouter, the {items,total} envelope (rejecting legacy {change_orders} that ChangeOrdersView.tsx reads via j.items), that type/costImpact/scheduleImpactDays are preserved (no silent amount:0), and that a budgets-only app 404s change-order paths; api/__tests__/changeOrdersAuthz.test.ts covers viewer/engineer→403 on approve/reject'],
  },
  {
    id: 'costcontrol', name: 'Cost Control', route: 'costcontrol', navigationSection: 'commercial',
    component: 'src/components/costControl/CostControlDashboard.tsx',
    status: 'VERIFIED_NATIVE', verification: 'audit',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/services/costControl/costControlService.ts',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Custom SVG charts; evm_baselines.is_active query fixed (P0-05).'],
    evidence: ['CLOSURE_EVIDENCE P0-05; CostControlDashboard.tsx'],
  },
  {
    id: 'costentry', name: 'Cost Entry', route: 'costentry', navigationSection: 'commercial',
    component: 'src/components/costEntry/CostEntryView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes (cost entry) → evm_actuals',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Posts actuals against WBS → Cost Control.'],
    evidence: ['CostEntryView.tsx header'],
  },
  {
    id: 'evm', name: 'EVM', route: 'evm', navigationSection: 'commercial',
    component: 'src/components/evm/EVMDashboard.tsx',
    status: 'VERIFIED_NATIVE', verification: 'audit',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/services/evm/evmService.ts',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['BCWS/BCWP/ACWP, SPI/CPI, EAC/ETC, SVG S-curve.'],
    evidence: ['EVMDashboard.tsx; EVM schema verified in INDEPENDENT_AUDIT data-model audit'],
  },
  {
    id: 'billing', name: 'Billing', route: 'billing', navigationSection: 'commercial',
    component: 'src/components/billing/BillingView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes (billing / pay applications)',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['AIA G702/G703 progress billing + continuation sheet (deterministic math).'],
    evidence: ['BillingView.tsx header: "AIA G702/G703 progress billing"'],
  },
  {
    id: 'costiq', name: 'Cost IQ', route: 'costiq', navigationSection: 'commercial',
    component: 'src/components/costControl/CostIntelligenceView.tsx',
    status: 'DETERMINISTIC_AUTOMATION', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes (cost intelligence)',
    productionSuitable: true, engineerReviewRequired: false,
    honestyIssue: '"IQ" implies AI; it is deterministic budget-drift explanation with cited drivers.',
    limitations: ['Deterministic variance explanation.'],
    evidence: ['CostIntelligenceView.tsx header'],
  },

  // ─── Turnover ────────────────────────────────────────────────────────────
  {
    id: 'turnover', name: 'Turnover', route: 'turnover', navigationSection: 'turnover',
    component: 'src/components/turnover/TurnoverView.tsx',
    status: 'PARTIAL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes (turnover packages) + external commissioning workspace handoff',
    externalDependency: 'external commissioning workspace (COMMISSIONING_EXTERNAL flag, off by default)',
    productionSuitable: false, engineerReviewRequired: false,
    limitations: ['Turnover packages manage a handoff to an external Cx workspace that is flag-gated off.'],
    evidence: ['TurnoverView.tsx header; commissioningGateway (feature-flagged) in INDEPENDENT_AUDIT'],
  },
  {
    id: 'transmittals', name: 'Transmittals', route: 'transmittals', navigationSection: 'turnover',
    component: 'src/components/TransmittalsView.tsx',
    status: 'PARTIAL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes/transmittals.ts (list/send/close real, mounted server.ts:608; POST / exists but unreached from UI)',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Downgraded from VERIFIED_NATIVE (independent review 2026-07-21): list, send, and close are real, but "+ New Transmittal" (TransmittalsView.tsx:203) is a toast stub — onClick fires showToast("Create transmittal — connect form to POST /api/v1/transmittals"). The POST route exists but no UI path reaches it, so a transmittal cannot be created in-app.',
    limitations: ['Create is a toast stub; list/send/close work. A user cannot originate a transmittal through the UI.'],
    evidence: ['TransmittalsView.tsx:203 toast stub; POST / at transmittals.ts:50 unreachable from UI; independent review 2026-07-21'],
  },
  {
    id: 'docs', name: 'Documents', route: 'docs', navigationSection: 'turnover',
    component: 'src/components/DocumentsView.tsx',
    status: 'PARTIAL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'legacy JarvisCore extraction (store); document ingest via api/services/knowledge*',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Legacy JarvisCore-extracted Documents module (store-backed); the real document-ingest + AI-summarized search lives in the Knowledge admin surface.',
    limitations: ['Store-backed legacy module; real ingest is under Knowledge.'],
    evidence: ['DocumentsView.tsx header: "Extraction of JarvisCore vn()"'],
  },

  // ─── Operations ──────────────────────────────────────────────────────────
  {
    id: 'portfolio', name: 'Portfolio', route: 'portfolio', navigationSection: 'operations',
    component: 'src/components/FinanceView.tsx',
    status: 'PARTIAL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'useBizStore (FinanceView: Summary/Invoices/Expenses/Journal)',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Nav label "Portfolio" maps to FinanceView (invoices/expenses/journal), store-backed and non-hydrated.',
    limitations: ['Store-backed finance tabs; label/route mismatch with content.'],
    evidence: ['ContentRouter TAB_MAP portfolio→FinanceView; FinanceView.tsx header'],
  },

  // ─── AI ──────────────────────────────────────────────────────────────────
  {
    id: 'coordination', name: 'Coordination', route: 'coordination', navigationSection: 'ai',
    component: 'src/components/copilot/CoordinationView.tsx',
    status: 'DETERMINISTIC_AUTOMATION', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/services/copilot/coordinationService.ts',
    productionSuitable: true, engineerReviewRequired: false,
    honestyIssue: 'In the "AI" nav section; surfaces missing approvals / dependency blockers / schedule + BIM clashes via deterministic rules, not an LLM.',
    limitations: ['Deterministic cross-module blocker detection.'],
    evidence: ['CoordinationView.tsx header: "Where is the project blocked ... deterministic"'],
  },
  {
    id: 'predict', name: 'Predict', route: 'predict', navigationSection: 'ai',
    component: 'src/components/predict/PredictView.tsx',
    status: 'PREDICTIVE_MODEL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: true,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/services/predict/predictService.ts',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Statistical prediction (portfolio health, EAC trend, anomaly flags) — not a trained/validated ML model and not an LLM; confidence values are heuristic.',
    limitations: ['Statistical/heuristic, not validated ML; underlying scores are deterministic (INDEPENDENT_AUDIT).'],
    evidence: ['PredictView.tsx header: "Statistical prediction"; INDEPENDENT_AUDIT AI-layer audit'],
  },
  {
    id: 'autopilot', name: 'Autopilot', route: 'autopilot', navigationSection: 'ai',
    component: 'src/components/copilot/AutopilotView.tsx',
    status: 'DETERMINISTIC_AUTOMATION', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/services/copilot (coordination recommendations)',
    productionSuitable: true, engineerReviewRequired: false,
    honestyIssue: '"Autopilot" implies autonomous AI; it is an execute-with-approval loop over deterministic coordination recommendations.',
    limitations: ['Deterministic recommendations → human approve/dismiss → tracked action.'],
    evidence: ['AutopilotView.tsx header: "execute-with-approval loop"'],
  },
  {
    id: 'ask', name: 'Ask Jarvis', route: 'ask', navigationSection: 'ai',
    component: 'src/components/AskJarvisView.tsx',
    status: 'GROUNDING_OR_RAG', verification: 'audit',
    llmUsed: true, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/services/askBuilder.ts (POST /api/v1/ask)',
    externalDependency: 'Anthropic Claude API (ANTHROPIC_API_KEY)',
    productionSuitable: true, engineerReviewRequired: false,
    honestyIssue: 'Must NOT present unimplemented engineering calculators as executable; its own prompt is honest ("answer ONLY from SOURCES") but the legacy JARVIS_SYSTEM_PROMPT (JarvisCore path) overclaims capabilities — corrected in this audit.',
    limitations: ['Grounded RAG with citations; budget-enforced; fails open only on lookup error. Budget/DP paths lack tests (P1-10/11).'],
    evidence: ['askBuilder.ts SYSTEM_PROMPT + client.messages.create; INDEPENDENT_AUDIT AI-layer audit'],
  },

  // ─── Executive ───────────────────────────────────────────────────────────
  {
    id: 'executive', name: 'Executive', route: 'executive', navigationSection: 'executive',
    component: 'src/components/copilot/ExecutiveView.tsx',
    status: 'DETERMINISTIC_AUTOMATION', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/services/copilot (executive briefing)',
    productionSuitable: true, engineerReviewRequired: false,
    honestyIssue: 'Board-level briefing; deterministic ("every ..." per header), not generative AI.',
    limitations: ['Deterministic portfolio-health briefing.'],
    evidence: ['ExecutiveView.tsx header: "Deterministic"'],
  },
  {
    id: 'portfolioiq', name: 'Portfolio IQ', route: 'portfolioiq', navigationSection: 'executive',
    component: 'src/components/copilot/PortfolioIQView.tsx',
    status: 'DETERMINISTIC_AUTOMATION', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/services/copilot (portfolio comparison)',
    productionSuitable: true, engineerReviewRequired: false,
    honestyIssue: '"IQ" implies AI; deterministic cross-project benchmarks + resource-conflict detection.',
    limitations: ['Deterministic cross-project analytics.'],
    evidence: ['PortfolioIQView.tsx header'],
  },
  {
    id: 'dash', name: 'Dashboard', route: 'dash', navigationSection: 'executive',
    component: 'src/components/Dashboard.tsx',
    status: 'PARTIAL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'useBizStore aggregation',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Executive KPI dashboard aggregating non-hydrated store collections.',
    limitations: ['Store-backed KPI tiles.'],
    evidence: ['Dashboard.tsx header'],
  },

  // ─── Administration ──────────────────────────────────────────────────────
  {
    id: 'automation', name: 'Automation', route: 'automation', navigationSection: 'admin',
    component: 'src/components/AutomationView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'code',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/services/scheduler.ts (background_jobs, scheduled_jobs)',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Scheduled + background job admin; scheduler promoter errors observed non-fatal (see SCHEDULER_PROMOTER_BASELINE).'],
    evidence: ['AutomationView.tsx header; scheduler.ts'],
  },
  {
    id: 'integrations', name: 'Integrations', route: 'integrations', navigationSection: 'admin',
    component: 'src/components/IntegrationsView.tsx',
    status: 'PARTIAL', verification: 'audit',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes/integrations.ts + api/services/integrationSync.ts',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'List/create/test/trigger works, but every connector sync type (Procore/SAP/Primavera/etc.) is a documented no-op stub — enabling one does nothing but log.',
    limitations: ['integrationSync is a no-op for all connector types (INDEPENDENT_AUDIT P2-02).'],
    evidence: ['IntegrationsView.tsx header; INDEPENDENT_AUDIT P2-02 integrationSync stub'],
  },
  {
    id: 'mcp', name: 'MCP', route: 'mcp', navigationSection: 'admin',
    component: 'src/components/MCPToolsPage.tsx',
    status: 'PARTIAL', verification: 'audit',
    llmUsed: true, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes/mcp.ts (native tools, incl. in-process Claude calls) + AVA_MCP_URL proxy',
    externalDependency: 'Ava MCP server (AVA_MCP_URL) — blank by default',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Corrected (independent review 2026-07-21): llmUsed set true — mcp.ts:75 instantiates Anthropic and the model_call/ask_domain/knowledge tools call Claude in-process with the backend ANTHROPIC_API_KEY. Native tool count is 10 (NATIVE_TOOLS), not "~6-9". Catalog advertises 43 tools; the other ~33 proxy to an unconfigured external Ava server (503 ava_not_configured). No @modelcontextprotocol SDK — hand-rolled REST. STILL PARTIAL for these reasons. The previously-noted audit-trail defect is now FIXED and merged (PR #23, merge 353525b): writeAudit/audit_query use the real audit_log columns (action/resource/new_data) with the valid integrate_push enum, a UUID-guarded actor, tenant-scoped queries, and ERROR-level logging on write failure (best-effort, not transactionally coupled to tool success).',
    limitations: ['~77% of catalog unreachable by default (unconfigured Ava proxy); in-process Claude calls present. MCP audit trail fixed (PR #23) — verified at code+contract tier (mocked pg pool), not live-DB persistence.'],
    evidence: ['mcp.ts:36,75 Anthropic SDK + :83/:368 model_call; NATIVE_TOOLS = 10 entries; audit fix — PR #23 merge 353525b (fix 2889431 + tests fd10af7): writeAudit inserts (action,resource,new_data) with integrate_push enum vs audit_log schema (migration 001), api/__tests__/mcp.test.ts asserts real columns/valid enum/non-UUID→NULL, ERROR-log on failure, and tenant-scoped audit_query; independent review 2026-07-21'],
  },
  {
    id: 'knowledge', name: 'Knowledge', route: 'knowledge', navigationSection: 'admin',
    component: 'src/components/KnowledgeView.tsx',
    status: 'VERIFIED_EXTERNAL', verification: 'code',
    llmUsed: true, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/services/knowledge* (ingest, embed, search)',
    externalDependency: 'embedding provider (OpenAI/Together) + Anthropic for summaries',
    productionSuitable: true, engineerReviewRequired: false,
    limitations: ['Document ingest + full-text/embedding search with citations; depends on external embedding provider.'],
    evidence: ['KnowledgeView.tsx header; embed.ts external provider calls'],
  },
  {
    id: 'system', name: 'System', route: 'system', navigationSection: 'admin',
    component: 'src/components/SettingsView.tsx',
    status: 'PARTIAL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'useBizStore (settings) + owner config',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Settings view hardcodes a version string ("v4.23.0") that disagrees with package.json and other surfaces (version drift, INDEPENDENT_AUDIT P2-08).',
    limitations: ['Store-backed settings; version-string drift.'],
    evidence: ['SettingsView.tsx; INDEPENDENT_AUDIT P2-08 version drift'],
  },

  // ─── Sub-tools (not their own route; launched from within a route) ───────
  {
    id: 'pid-pfd-generator', name: 'P&ID / PFD Generator', route: undefined,
    component: 'public/tools/denver/UNIVERSAL-PID-GENERATOR.js, TRUE-PID-GENERATOR.js (launched from Calc/Process Design)',
    status: 'BROKEN_OR_DEAD', verification: 'audit',
    llmUsed: false, deterministicRulesUsed: true, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'public/tools/denver/*.js (client-side canvas; SVG/DXF export not wired)',
    productionSuitable: false, engineerReviewRequired: true,
    honestyIssue: 'Downgraded from DRAWING_GENERATOR (independent review 2026-07-21) — this was the audit’s only affirmative "genuinely real" claim and it does not survive inspection. (a) pid-universal.html always hits a placeholder fallback: it probes for generatePFD/PIDGenerator/DenverPFD but the script defines only class UniversalPIDGenerator, then reports "PFD generated ✓". (b) pid-true.html:110 passes args in the wrong order and calls generateGenericPID/generateHVACPID/generateWaterPID/generateStormwaterPID, none of which are defined → TypeError every run. (c) Both generators are HTML5 Canvas, not SVG; generateSVG() is a stub returning an empty rectangle. (d) DXF export is a stub — exportToPIDDXF is undefined repo-wide; the "DXF Export" button downloads an SVG. Correct status is BROKEN_OR_DEAD, not a working drawing generator.',
    limitations: ['PFD path renders a placeholder; TRUE P&ID path throws; no SVG output; "DXF export" downloads SVG. Real ISA geometry exists only on the canvas and is never emitted.'],
    evidence: ['pid-universal.html:82-85 symbol-name probe vs class UniversalPIDGenerator; pid-true.html:110 arg order + undefined methods; UNIVERSAL-PID-GENERATOR.js:1614-1620 generateSVG stub; pid-true.html:131-144 exportDXF fallback, exportToPIDDXF undefined repo-wide; independent review 2026-07-21'],
  },

  // ─── Hidden / legacy (reachable via TAB_MAP, not in the sidebar) ─────────
  {
    id: 'commissioning', name: 'Commissioning (hidden)', route: 'commissioning',
    component: 'src/components/CommissioningView.tsx',
    status: 'PARTIAL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes (commissioning); only the workflow tab (CxWorkflowView) calls it',
    externalDependency: 'external Cx workspace (COMMISSIONING_EXTERNAL flag, off)',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Downgraded from VERIFIED_NATIVE (independent review 2026-07-21): hidden route (TAB_MAP only), AND 3 of 4 tabs are store-backed. CommissioningView.tsx makes no fetch of its own; :272-274 read selectCloseouts/selectPunchItems/selectLessons from useBizStore — all in the non-hydrated set (store.ts:235-238) — and ContentRouter passes no such props, so the store fallback always applies. Only the workflow tab (CxWorkflowView) is backend-real; the default landing tab is "completion", a permanently empty store view. By the registry’s own engineering-hub precedent this is PARTIAL.',
    limitations: ['Default/completion/punch/lessons tabs render from the non-hydrated biz store; only the workflow tab is backend-wired. External gateway flag-gated off.'],
    evidence: ['CommissioningView.tsx:272-274 useBizStore + :280 default tab "completion"; store.ts:235-238 non-hydrated; CxWorkflowView.tsx backend calls; independent review 2026-07-21'],
  },
  {
    id: 'engineering-hub', name: 'Engineering hub (hidden)', route: 'engineering',
    component: 'src/components/EngineeringView.tsx',
    status: 'PARTIAL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'useBizStore',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Legacy store-backed hub, reachable via TAB_MAP but not in the sidebar.',
    limitations: ['Hidden legacy route.'],
    evidence: ['ContentRouter TAB_MAP engineering→EngineeringView; not in navigation.ts'],
  },
  {
    id: 'audit-log', name: 'Audit Log (hidden)', route: 'audit',
    component: 'src/components/AuditLogView.tsx',
    status: 'VERIFIED_NATIVE', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'api/routes (audit_log reader) + CSV export',
    productionSuitable: true, engineerReviewRequired: false,
    honestyIssue: 'Real tenant-scoped audit reader, but reachable only via TAB_MAP/deep-link, not the sidebar.',
    limitations: ['Hidden route; no sidebar entry.'],
    evidence: ['AuditLogView.tsx header; ContentRouter TAB_MAP audit→AuditLogView'],
  },
  {
    id: 'overview-hidden', name: 'Overview (hidden)', route: 'overview',
    component: 'src/components/DashboardMainView.tsx',
    status: 'PARTIAL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'wraps HubView (store aggregation)',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Hidden route wrapping HubView; duplicate of Eng Hub aggregation.',
    limitations: ['Hidden; store-backed.'],
    evidence: ['DashboardMainView.tsx imports HubView; TAB_MAP overview'],
  },
  {
    id: 'plan-hidden', name: 'Planner (hidden)', route: 'plan',
    component: 'src/components/PlannerView.tsx',
    status: 'PARTIAL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'composes LoView/BiView (store)',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Hidden legacy composite route, not in the sidebar.',
    limitations: ['Hidden; store-backed.'],
    evidence: ['ContentRouter TAB_MAP plan→PlannerView; not in navigation.ts'],
  },
  {
    id: 'resources-hidden', name: 'Resources (hidden)', route: 'resources',
    component: 'src/components/ResourcesView.tsx',
    status: 'PARTIAL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'composes LiView (store)',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Hidden legacy route, not in the sidebar.',
    limitations: ['Hidden; store-backed.'],
    evidence: ['ContentRouter TAB_MAP resources→ResourcesView; not in navigation.ts'],
  },
  {
    id: 'jobs-hidden', name: 'Jobs (hidden)', route: 'jobs',
    component: 'src/components/JobsView.tsx',
    status: 'PARTIAL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'useBizStore',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Hidden legacy route, not in the sidebar.',
    limitations: ['Hidden; store-backed.'],
    evidence: ['ContentRouter TAB_MAP jobs→JobsView; not in navigation.ts'],
  },
  {
    id: 'procurement-hub', name: 'Procurement hub (hidden)', route: 'procurement',
    component: 'src/components/ProcurementView.tsx',
    status: 'PARTIAL', verification: 'code',
    llmUsed: false, deterministicRulesUsed: false, predictiveModelUsed: false,
    engineeringCalculation: false, calculationValidated: false, drawingGeneration: false,
    backendLocation: 'legacy JarvisCore extraction (store)',
    productionSuitable: false, engineerReviewRequired: false,
    honestyIssue: 'Legacy store-backed procurement hub reachable via TAB_MAP; the sidebar uses the newer subcontracts/directory/etc. routes instead.',
    limitations: ['Hidden legacy hub.'],
    evidence: ['ProcurementView.tsx header: "Extraction of JarvisCore fn()"; TAB_MAP procurement'],
  },
]

/**
 * Routable ids that are intentionally NOT given full capability entries.
 * The guard treats these as acknowledged rather than missing.
 */
export const EXCLUDED_ROUTES: { route: string; reason: string }[] = []

/** Fast lookup by route id. */
export function capabilityForRoute(route: string): Capability | undefined {
  return CAPABILITIES.find(c => c.route === route)
}
